allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@bruits/satteri-darwin-arm64@0.9.3'
  - '@bruits/satteri-darwin-x64@0.9.3'
  - '@bruits/satteri-linux-arm64-gnu@0.9.3'
  - '@bruits/satteri-linux-arm64-musl@0.9.3'
  - '@bruits/satteri-linux-x64-gnu@0.9.3'
  - '@bruits/satteri-linux-x64-musl@0.9.3'
  - '@bruits/satteri-wasm32-wasi@0.9.3'
  - '@bruits/satteri-win32-arm64-msvc@0.9.3'
  - '@bruits/satteri-win32-x64-msvc@0.9.3'
  - satteri@0.9.3
  - starlight-links-validator@0.25.1
